# ─────────────────────────────────────────────────────────────
# AUTOSTART
# ─────────────────────────────────────────────────────────────

# Setup XDG Desktop Portal environment
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Polkit Authentication Agent
exec-once = systemctl --user start hyprpolkitagent.service || /usr/lib/hyprpolkitagent || /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Status bar
exec-once = ~/.config/waybar/launch.sh

# Notification Daemon
exec-once = swaync

# Idle & Screen Lock
exec-once = hypridle

# Wallpaper Daemon & Restore Wallpaper
exec-once = ~/.config/hypr/scripts/wallpaper.sh --restore

# Clipboard Manager
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Network Manager Applet
exec-once = nm-applet --indicator

# Reset session cache
exec-once = rm -f ~/.cache/dotfiles/gamemode
