# ─────────────────────────────────────────────────────────────
# DECORATIONS, WINDOWS & LAYOUT
# ─────────────────────────────────────────────────────────────

# Fallback color variables (overridden by dynamic matugen colors.conf)
$primary = rgba(c6c6c7ff)
$on_primary = rgba(303031ff)

# General window layout & borders
general {
    gaps_in = 10
    gaps_out = 20
    border_size = 2
    col.active_border = $primary $on_primary 90deg
    col.inactive_border = $on_primary
    layout = dwindle
    resize_on_border = true
}

# Window decoration (blur, rounding, shadow)
decoration {
    rounding = 10
    active_opacity = 1.0
    inactive_opacity = 0.9
    fullscreen_opacity = 1.0

    blur {
        enabled = true
        size = 4
        passes = 4
        new_optimizations = on
        ignore_opacity = true
        xray = true
    }

    shadow {
        enabled = true
        range = 32
        render_power = 2
        color = rgba(00000050)
    }
}

# Layout engines
dwindle {
    preserve_split = true
}

master {
    # new_status = master
}

# Miscellaneous window behavior
misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    initial_workspace_tracking = 1
    on_focus_under_fullscreen = 1
    allow_session_lock_restore = true
}

binds {
    workspace_back_and_forth = false
    allow_workspace_cycles = true
    pass_mouse_when_bound = false
}
