# ─────────────────────────────────────────────────────────────
# WINDOW & LAYER RULES — Default
# ─────────────────────────────────────────────────────────────

# Suppress maximize events
windowrulev2 = suppressevent maximize, class:.*

# Floating tools & dialogs
windowrulev2 = float, class:^(pavucontrol|org\.pulseaudio\.pavucontrol)$
windowrulev2 = center, class:^(pavucontrol|org\.pulseaudio\.pavucontrol)$
windowrulev2 = size 700 550, class:^(pavucontrol|org\.pulseaudio\.pavucontrol)$

windowrulev2 = float, class:^(blueman-manager)$
windowrulev2 = float, class:^(nm-connection-editor)$
windowrulev2 = float, class:^(nwg-look)$
windowrulev2 = float, class:^(qt6ct)$

# File dialogs / pin
windowrulev2 = float, title:^(Open File|Open Folder|Save As|File Upload)$

# Kitty opacity
windowrulev2 = opacity 0.95 0.98, class:^(kitty)$

# SwayNC Layer Rules
layerrule = blur, swaync-control-center
layerrule = blur, swaync-notification-window
layerrule = ignorezero, swaync-control-center
layerrule = ignorezero, swaync-notification-window
layerrule = ignorealpha 0.5, swaync-control-center
layerrule = ignorealpha 0.5, swaync-notification-window

# Waybar Layer Rules
layerrule = blur, waybar
layerrule = ignorezero, waybar

# Rofi Layer Rules
layerrule = blur, rofi
layerrule = ignorezero, rofi
